version: "3"
services:
  mysql:
    image: mysql:latest
    platform:
      linux/arm64
    container_name: mysql-students-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentsDatabase
    ports:
      - "3306:3306"